theme = "devision-docs"

canonifyURLs = true

languageCode = "ru-ru"
DefaultContentLanguage = "ru"

title = "{{cookiecutter.project_name}} | Devision Developers"

[params]
projectName = "{{cookiecutter.project_name}}"

noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = true # default is false
ordersectionsby = "weight"

[outputs]
home = [ "HTML", "RSS", "JSON"]

